# Generated by Django 2.2.2 on 2019-06-17 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactdetails',
            options={'verbose_name': 'contact details', 'verbose_name_plural': 'contact details'},
        ),
    ]
