# Generated by Django 2.2.2 on 2019-06-17 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_reserve'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category/'),
        ),
    ]
