# Generated by Django 2.2.2 on 2019-06-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_property_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='major',
            field=models.BooleanField(default=False),
        ),
    ]
